name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: 'flutter'
  cupertino_icons: ^1.0.5
  scrollable_positioned_list_extended: ^0.3.8
  chatview:
    path: ../
  uuid: ^3.0.7
  scroll_to_index: ^3.0.1
  moxxmpp:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: 0.2.0
  moxxmpp_socket_tcp:
    hosted: https://git.polynom.me/api/packages/Moxxy/pub
    version: 0.2.1
  sticky_grouped_list:
    git:
      url: https://github.com/Yogesh-Dubey-Ayesavi/sticky_grouped_list.git  
  get_it: ^7.4.1

dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
