name: flutter_chatbook
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 0.0.2-alpha
issue_tracker: https://github.com/Yogesh-Dubey-Ayesavi/flutter_chatbook/issues
repository: https://github.com/Yogesh-Dubey-Ayesavi/flutter_chatbook

platforms:
  android:
  ios:
  web:


environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: 'flutter'
  grouped_list: ^5.1.2
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.7
  emoji_picker_flutter: ^1.3.0
  html: ^0.15.1
  any_link_preview: ^3.0.1
  progress_indicators: ^1.0.0
  audio_waveforms: ^1.0.1
  # For formatting time locale in message receipts
  # timeago: ^3.4.0 
  equatable: ^2.0.5
  meta: ^1.8.0
  scrollable_positioned_list_extended: ^0.3.9
  flutter_parsed_text: ^2.2.1
  swipeable_tile: ^2.0.0+3
  scroll_to_index: ^3.0.1
  vibration: ^1.7.6
  sqflite: ^2.2.6
  path: ^1.8.2
  get_it: ^7.2.0
  json_annotation: ^4.8.0
  flutter_markdown: ^0.6.14
  intl: ^0.18.1
  uuid: ^3.0.7
  parsed_readmore: ^0.0.6
  characters: ^1.3.0
  http: ^1.0.0
  image_picker: ^0.8.7+5

  

dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  lints: ^2.0.1

flutter:

