name: Flutter Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'  

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.8'
          channel: 'stable'

      - name: Display Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get
      
      - name: Format Code
        run: dart format ./
